;;; Automatically generated by ‘recentf’ on Thu Aug 21 06:52:18 2025.

(setq recentf-list
      '(
        "/Users/chris/.ido.last"
        "/Volumes/Things/account_mapping.json"
        "/Users/chris/Dropbox/Private/diary.txt"
        "/Users/chris/Dropbox/Private/projects.txt"
        "/Users/chris/Dropbox/Private/rap.txt"
        "/Users/chris/.emacs.d/init.el"
        "/Users/chris/Dropbox/Property/Reeds Avenue/Lounge 2025/SRS-agreement.txt"
        "/Users/chris/Downloads/game.py"
        "/Users/chris/.zshenv"
        "/Users/chris/Library/Preferences/Aquamacs Emacs/Preferences.el"
        "/Users/chris/.emacs"
        "/Users/chris/.emacs.d/crontab.el"
        "/Users/chris/.emacs.d/README.txt"
        "/Users/chris/.claude.json"
        "/Users/chris/Downloads/moneybox_pytest_fixtures_migration.md"
        "/Users/chris/.bashrc"
        "/Users/chris/.docker/config.json"
        "/Users/chris/.claude/settings.json"
        "/Users/chris/Downloads/claude-instructions.md"
        "/Users/chris/Downloads/CLAUDE_PLAN.md"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
